services:
  db:
    build: .
    container_name: kg-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pwd
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - kgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    # AGE requires shared_preload_libraries
    command: >
      postgres
        -c shared_preload_libraries='age'
        -c search_path='"$$user",public,ag_catalog'

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: kg-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  kgdata:
