// Centralized icon imports for the Multi-Agent Travel Planner UI
// Generated by asset-generator using Azure OpenAI gpt-image-1.5

// Agent icons
import agentFacilitator from '../assets/icons/agent-facilitator.png';
import agentLogistics from '../assets/icons/agent-logistics.png';
import agentSightseeing from '../assets/icons/agent-sightseeing.png';
import agentExperience from '../assets/icons/agent-experience.png';
import agentFood from '../assets/icons/agent-food.png';

// Section header icons
import appIcon from '../assets/icons/app-icon.png';
import timelineIcon from '../assets/icons/timeline.png';
import chatIcon from '../assets/icons/chat.png';
import taskboardIcon from '../assets/icons/taskboard.png';
import documentIcon from '../assets/icons/document.png';

// Status / action icons
import globeIcon from '../assets/icons/globe.png';
import toolIcon from '../assets/icons/tool.png';
import rocketIcon from '../assets/icons/rocket.png';
import finishFlagIcon from '../assets/icons/finish-flag.png';
import messageIcon from '../assets/icons/message.png';
import warningIcon from '../assets/icons/warning.png';
import checkmarkIcon from '../assets/icons/checkmark.png';
import hourglassIcon from '../assets/icons/hourglass.png';

export const icons = {
  // Agents
  agentFacilitator,
  agentLogistics,
  agentSightseeing,
  agentExperience,
  agentFood,

  // Sections
  appIcon,
  timelineIcon,
  chatIcon,
  taskboardIcon,
  documentIcon,

  // Status
  globeIcon,
  toolIcon,
  rocketIcon,
  finishFlagIcon,
  messageIcon,
  warningIcon,
  checkmarkIcon,
  hourglassIcon,
} as const;

// Map agent name → agent icon for easy lookup
export const AGENT_ICONS: Record<string, string> = {
  facilitator: agentFacilitator,
  logistics: agentLogistics,
  sightseeing: agentSightseeing,
  experience: agentExperience,
  food: agentFood,
};

// Helper component-style inline size (px)
export const ICON_SM = 16;
export const ICON_MD = 20;
export const ICON_LG = 28;
